export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#dae2fd',
        'secondary-container': '#fe932c',
        'surface-tint': '#396285',
        'on-error-container': '#93000a',
        'on-primary-container': '#7fa7cd',
        'on-tertiary-fixed-variant': '#005323',
        'error-container': '#ffdad6',
        'on-surface-variant': '#42474e',
        'secondary-fixed-dim': '#ffb77d',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#2f1500',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#ffdcc3',
        'surface-container': '#eaedff',
        'inverse-surface': '#283044',
        'on-primary': '#ffffff',
        'on-background': '#131b2e',
        'tertiary-container': '#00431b',
        'inverse-on-surface': '#eef0ff',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'surface-dim': '#d2d9f4',
        'background': '#faf8ff',
        'outline': '#72777e',
        'primary': '#00263f',
        'primary-container': '#0b3c5d',
        'primary-fixed-dim': '#a3cbf2',
        'inverse-primary': '#a3cbf2',
        'on-secondary-container': '#663500',
        'tertiary': '#002b0f',
        'on-primary-fixed': '#001d32',
        'on-primary-fixed-variant': '#1f4a6c',
        'on-tertiary-container': '#55b66c',
        'secondary': '#904d00',
        'tertiary-fixed-dim': '#79db8d',
        'on-surface': '#131b2e',
        'primary-fixed': '#cee5ff',
        'tertiary-fixed': '#95f8a7',
        'on-tertiary-fixed': '#00210a',
        'surface': '#faf8ff',
        'outline-variant': '#c2c7ce',
        'surface-container-high': '#e2e7ff',
        'surface-variant': '#dae2fd',
        'on-secondary-fixed-variant': '#6e3900',
        'surface-bright': '#faf8ff',
        'surface-container-low': '#f2f3ff',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-lg': '1.5rem',
        'gutter-md': '1.5rem',
        'margin-lg': '3rem',
        'space-xl': '2rem',
        'margin-md': '2rem',
        'gutter-lg': '2rem',
        'margin': '1rem',
        'space-xs': '0.25rem',
        'gutter': '1rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
      },
      fontSize: {
        'title-lg': ['18px', { lineHeight: '26px', fontWeight: '700' }],
        'display-lg-mobile': ['30px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-sm': ['14px', { lineHeight: '22px', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '34px', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'display-lg': ['40px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '38px', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '32px', fontWeight: '600' }],
      },
      fontFamily: {
        sans: ['Noto Sans', 'Inter', 'sans-serif'],
        'title-lg': ['Noto Sans', 'Inter', 'sans-serif'],
        'display-lg-mobile': ['Noto Sans', 'Inter', 'sans-serif'],
        'title-sm': ['Noto Sans', 'Inter', 'sans-serif'],
        'body-sm': ['Noto Sans', 'Inter', 'sans-serif'],
        'headline-lg-mobile': ['Noto Sans', 'Inter', 'sans-serif'],
        'label-sm': ['Noto Sans', 'Inter', 'sans-serif'],
        'headline-sm': ['Noto Sans', 'Inter', 'sans-serif'],
        'body-md': ['Noto Sans', 'Inter', 'sans-serif'],
        'label-md': ['Noto Sans', 'Inter', 'sans-serif'],
        'display-lg': ['Noto Sans', 'Inter', 'sans-serif'],
        'label-lg': ['Noto Sans', 'Inter', 'sans-serif'],
        'title-md': ['Noto Sans', 'Inter', 'sans-serif'],
        'body-lg': ['Noto Sans', 'Inter', 'sans-serif'],
        'headline-lg': ['Noto Sans', 'Inter', 'sans-serif'],
        'headline-md': ['Noto Sans', 'Inter', 'sans-serif'],
      },
    },
  },
}
