export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Core palette ──────────────────────────────────────────────────
        chassis: "#f5f0e9",
        panel: "#f5f0e9",
        recessed: "#d9cbc2",
        ink: "#112250",
        "ink-muted": "#3c5070",
        accent: {
          DEFAULT: "#e0c58f",
          foreground: "#f5f0e9",
          hover: "#ead4a8",
          shadow: "rgba(17,34,80,0.35)",
        },
        "industrial-border": {
          DEFAULT: "#d9cbc2",
          shadow: "#c8b9b0",
          light: "#f5f0e9",
          dark: "#3c5070",
        },
        // ── Industrial-* aliases (used by refactored pages) ───────────────
        "industrial-chassis": "#f5f0e9",
        "industrial-panel": "#f5f0e9",
        "industrial-recessed": "#d9cbc2",
        "industrial-ink": "#112250",
        "industrial-ink-light": "#3c5070",
        "industrial-ink-muted": "#3c5070",
        "industrial-accent": "#e0c58f",
        "surface-container-highest": "#d9cbc2",
        "secondary-container": "#e0c58f",
        "surface-tint": "#3c5070",
        "on-error-container": "#93000a",
        "on-primary-container": "#ffffff",
        "on-tertiary-fixed-variant": "#005323",
        "error-container": "#ffdad6",
        "on-surface-variant": "#3c5070",
        "secondary-fixed-dim": "#ffd1d6",
        "surface-container-lowest": "#f0f2f5",
        "on-secondary-fixed": "#112250",
        "on-secondary": "#112250",
        "secondary-fixed": "#ead4a8",
        "surface-container": "#d9cbc2",
        "inverse-surface": "#112250",
        "on-primary": "#f5f0e9",
        "on-background": "#112250",
        "tertiary-container": "#22c55e",
        "inverse-on-surface": "#f5f0e9",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        error: "#ff4757",
        "surface-dim": "#d1d9e6",
        background: "#f5f0e9",
        outline: "#3c5070",
        primary: "#112250",
        "primary-container": "#112250",
        "primary-fixed-dim": "#d9cbc2",
        "inverse-primary": "#f5f0e9",
        "on-secondary-container": "#112250",
        tertiary: "#22c55e",
        "on-primary-fixed": "#f5f0e9",
        "on-primary-fixed-variant": "#d9cbc2",
        "on-tertiary-container": "#f5f0e9",
        secondary: "#e0c58f",
        "tertiary-fixed-dim": "#86efac",
        "on-surface": "#112250",
        "primary-fixed": "#f5f0e9",
        "tertiary-fixed": "#ead4a8",
        "on-tertiary-fixed": "#112250",
        surface: "#f5f0e9",
        "outline-variant": "#d9cbc2",
        "surface-container-high": "#eadfd6",
        "surface-variant": "#d9cbc2",
        "on-secondary-fixed-variant": "#112250",
        "surface-bright": "#f5f0e9",
        "surface-container-low": "#f5f0e9",
      },
      boxShadow: {
        card: "8px 8px 16px rgba(17,34,80,0.16), -8px -8px 16px #f5f0e9",
        floating:
          "12px 12px 24px rgba(17,34,80,0.18), -12px -12px 24px #f5f0e9, inset 1px 1px 0 rgba(245,240,233,0.65)",
        pressed:
          "inset 6px 6px 12px rgba(17,34,80,0.16), inset -6px -6px 12px #f5f0e9",
        recessed:
          "inset 4px 4px 8px rgba(17,34,80,0.14), inset -4px -4px 8px #f5f0e9",
        sharp:
          "4px 4px 8px rgba(0,0,0,0.15), -1px -1px 1px rgba(255,255,255,0.8)",
        glow: "0 0 10px 2px rgba(224, 197, 143, 0.7)",
        "glow-green": "0 0 10px 2px rgba(34, 197, 94, 0.7)",
        "btn-primary":
          "4px 4px 8px rgba(17,34,80,0.35), -4px -4px 8px rgba(245,240,233,0.75)",
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "8px",
        lg: "16px",
        xl: "24px",
        "2xl": "32px",
        full: "9999px",
      },
      spacing: {
        "space-lg": "1.5rem",
        "gutter-md": "1.5rem",
        "margin-lg": "3rem",
        "space-xl": "2rem",
        "margin-md": "2rem",
        "gutter-lg": "2rem",
        margin: "1rem",
        "space-xs": "0.25rem",
        gutter: "1rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
      },
      fontSize: {
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "700" }],
        "display-lg-mobile": [
          "30px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "title-sm": ["14px", { lineHeight: "22px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "34px", fontWeight: "700" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "600" },
        ],
        "headline-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "display-lg": [
          "40px",
          { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "38px", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "32px", fontWeight: "600" }],
      },
      fontFamily: {
        sans: ["Inter", "Noto Sans", "sans-serif"],
        mono: ["JetBrains Mono", "Roboto Mono", "ui-monospace", "monospace"],
        "title-lg": ["Inter", "Noto Sans", "sans-serif"],
        "display-lg-mobile": ["Inter", "Noto Sans", "sans-serif"],
        "title-sm": ["Inter", "Noto Sans", "sans-serif"],
        "body-sm": ["Inter", "Noto Sans", "sans-serif"],
        "headline-lg-mobile": ["Inter", "Noto Sans", "sans-serif"],
        "label-sm": ["JetBrains Mono", "Roboto Mono", "monospace"],
        "headline-sm": ["Inter", "Noto Sans", "sans-serif"],
        "body-md": ["Inter", "Noto Sans", "sans-serif"],
        "label-md": ["JetBrains Mono", "Roboto Mono", "monospace"],
        "display-lg": ["Inter", "Noto Sans", "sans-serif"],
        "label-lg": ["Inter", "Noto Sans", "sans-serif"],
        "title-md": ["Inter", "Noto Sans", "sans-serif"],
        "body-lg": ["Inter", "Noto Sans", "sans-serif"],
        "headline-lg": ["Inter", "Noto Sans", "sans-serif"],
        "headline-md": ["Inter", "Noto Sans", "sans-serif"],
      },
    },
  },
};
